"""Generated by tools/make_fixtures.py; pure confirmed-action readiness regressions."""
import argparse
import ast
import builtins
import copy
import io
import json
import math
from pathlib import Path
from types import SimpleNamespace
import unittest

ROOT = Path(__file__).resolve().parents[1]


def click_source():
    return (ROOT / "skills/screen-vision/scripts/click.py").read_bytes()


def record():
    return {
        "id": 0, "type": "button", "label": "Acme action", "name": "Acme action",
        "automation_id": "acme-action", "class_name": "Button", "source": "uia",
        "rect": [10, 20, 50, 60], "center": [30, 40], "enabled": True,
        "offscreen": False, "clickable": True, "patterns": ["Invoke"],
        "captured_at": 1000.0, "capture_rect": [0, 0, 200, 200],
        "identity": {
            "runtime_id": [42, 7], "window_runtime_id": [42, 1],
            "window": {"hwnd": 101, "pid": 202, "process_started": 303,
                       "rect": [0, 0, 200, 200]},
        },
    }


class World:
    """Run actual action/CLI definitions against an entirely in-memory desktop."""
    def __init__(self, ready=True, *, change_at=None, changed=False,
                 pattern=True, dispatch_failure=False):
        self.saved = record()
        self.ready, self.changed, self.change_at = ready, changed, change_at
        self.pattern, self.dispatch_failure = pattern, dispatch_failure
        self.events, self.actions, self.output = [], [], []
        self.argv = []
        world = self

        class Control:
            def __init__(self, runtime, children=()):
                self.runtime, self.children = runtime, list(children)

            def GetChildren(self):
                return self.children

            @property
            def BoundingRectangle(self):
                return SimpleNamespace(**dict(zip(("left", "top", "right", "bottom"),
                                                 world.saved["rect"])))

            @property
            def Name(self): return world.saved["name"]
            @property
            def AutomationId(self): return world.saved["automation_id"]
            @property
            def ClassName(self): return world.saved["class_name"]
            @property
            def ControlTypeName(self): return "ButtonControl"
            @property
            def IsEnabled(self): return True
            @property
            def IsOffscreen(self): return False

            def GetInvokePattern(self):
                world.events.append("pattern")
                world.change("pattern")
                return self if world.pattern else None

            def GetTogglePattern(self): return None
            def GetSelectionItemPattern(self): return None
            def GetExpandCollapsePattern(self): return None

            def Invoke(self):
                world.dispatch("invoke")

        self.control = Control([42, 7])
        self.root = Control([42, 1], [self.control])

        def from_handle(handle):
            self.events.append("resolve")
            self.change("resolve")
            assert handle == 101
            return self.root

        def from_point(x, y):
            self.events.append("hit")
            self.change("hit")
            assert [x, y] == [30, 40]
            return self.control

        def identity(control, root):
            assert control is self.control and root is self.root
            self.events.append("identity")
            return copy.deepcopy(self.saved["identity"])

        self.auto = SimpleNamespace(ControlFromHandle=from_handle, ControlFromPoint=from_point)
        self.common = SimpleNamespace(
            IS_WINDOWS=True, has_interactive_desktop=self.readiness,
            require_physical_coordinates=lambda: self.events.append("dpi"),
            runtime_id=lambda control: control.runtime, control_identity=identity,
            click_physical=lambda *args, **kwargs: self.dispatch("coord"),
        )

        def importing(name, *args, **kwargs):
            if name != "uiautomation":
                raise AssertionError("unexpected action import: " + name)
            self.events.append("uia_import")
            return self.auto

        class Parser(argparse.ArgumentParser):
            def parse_args(self, args=None, namespace=None):
                return super().parse_args(world.argv if args is None else args, namespace)

        def input_file(path, *args, **kwargs):
            assert path == "synthetic-elements.json"
            return io.StringIO(json.dumps([self.saved]))

        self.namespace = {
            "__doc__": "Synthetic confirmed-action contract.",
            "__builtins__": dict(vars(builtins), __import__=importing),
            "C": self.common, "math": math, "json": json,
            "time": SimpleNamespace(time=lambda: 1001.0, monotonic=lambda: 1.0),
            "argparse": SimpleNamespace(ArgumentParser=Parser),
            "open": input_file, "print": lambda value: self.output.append(json.loads(value)),
        }
        required = {"ActionError", "find_element", "validate_capture", "validate_control",
                    "resolve_element", "act_on_element", "main", "MAX_CAPTURE_AGE", "PATTERNS"}
        allowed = required | {"require_ready_desktop"}
        selected, found = [], set()
        for node in ast.parse(click_source(), "actual-click.py").body:
            if isinstance(node, (ast.FunctionDef, ast.ClassDef)) and node.name in allowed:
                selected.append(node)
                found.add(node.name)
            elif isinstance(node, ast.Assign) and len(node.targets) == 1:
                target = node.targets[0]
                if isinstance(target, ast.Name) and target.id in required:
                    selected.append(node)
                    found.add(target.id)
        if not required <= found:
            raise AssertionError("actual action definition selection is incomplete")
        exec(compile(ast.Module(body=selected, type_ignores=[]), "actual-click.py", "exec"),
             self.namespace)

    def change(self, phase):
        if phase == self.change_at:
            self.ready = self.changed

    def readiness(self):
        self.events.append("readiness")
        if isinstance(self.ready, Exception):
            raise self.ready
        return self.ready

    def dispatch(self, method):
        self.events.append("dispatch:" + method)
        self.actions.append(method)
        if self.dispatch_failure:
            raise RuntimeError("synthetic failure after dispatch started")
        return True

    def cli(self, method="auto", confirm=True, explicit_preview=False):
        self.argv = ["--elements-json", "synthetic-elements.json", "--id", "0",
                     "--method", method]
        if confirm:
            self.argv.append("--confirm")
        elif explicit_preview:
            self.argv.append("--dry-run")
        code = self.namespace["main"]()
        assert len(self.output) == 1
        return code, self.output[0]


class Screen18ReadinessTests(unittest.TestCase):
    def assert_refused(self, world, result):
        code, report = result
        self.assertEqual(code, 5)
        self.assertIs(report["ok"], False)
        self.assertIs(report["acted"], False)
        self.assertEqual(report["error"], "no_interactive_desktop")
        self.assertEqual(world.actions, [])

    def test_initial_readiness_refuses_all_confirmed_methods(self):
        for state in (False, None, 1, "ready", OSError("synthetic query failure")):
            for method in ("auto", "invoke", "coord"):
                with self.subTest(state=repr(state), method=method):
                    world = World(state)
                    self.assert_refused(world, world.cli(method))
                    self.assertEqual(world.events, ["dpi", "readiness"])

    def test_resolver_rejects_unready_before_uia(self):
        for state in (False, None, 1, "ready", RuntimeError("synthetic query failure")):
            with self.subTest(state=repr(state)):
                world = World(state)
                with self.assertRaises(world.namespace["ActionError"]) as caught:
                    world.namespace["resolve_element"](world.saved)
                self.assertEqual(caught.exception.code, "no_interactive_desktop")
                self.assertEqual(world.events, ["dpi", "readiness"])
                self.assertEqual(world.actions, [])

    def test_readiness_change_during_resolution_or_lookup_blocks_dispatch(self):
        scenarios = [
            ("invoke", "resolve", True), ("invoke", "pattern", True),
            ("auto", "pattern", True), ("coord", "resolve", True),
            ("coord", "hit", True), ("auto", "hit", False),
        ]
        for method, phase, pattern in scenarios:
            for state in (False, None, OSError("synthetic late query failure")):
                with self.subTest(method=method, phase=phase, state=repr(state)):
                    world = World(change_at=phase, changed=state, pattern=pattern)
                    self.assert_refused(world, world.cli(method))
                    self.assertEqual(world.events.count("readiness"), 2)
                    self.assertEqual(world.events[-1], "readiness")
                    self.assertLess(world.events.index("readiness"),
                                    world.events.index("uia_import"))
                    self.assertIn(phase, world.events)

    def test_ready_actions_keep_exact_dispatch_and_query_order(self):
        for method, pattern, dispatched in (
            ("invoke", True, "invoke"), ("auto", True, "invoke"),
            ("coord", True, "coord"), ("auto", False, "coord"),
        ):
            with self.subTest(method=method, pattern=pattern):
                world = World(pattern=pattern)
                code, report = world.cli(method)
                self.assertEqual(code, 0)
                self.assertIs(report["acted"], True)
                self.assertEqual(world.actions, [dispatched])
                self.assertEqual(world.events.count("readiness"), 2)
                self.assertEqual(world.events[-2:], ["readiness", "dispatch:" + dispatched])
                self.assertLess(world.events.index("readiness"),
                                world.events.index("uia_import"))

    def test_dry_preview_avoids_readiness_resolution_and_dispatch(self):
        for explicit in (False, True):
            with self.subTest(explicit_dry_run=explicit):
                world = World(RuntimeError("preview must not query readiness"))
                world.saved.pop("identity")
                code, report = world.cli(confirm=False, explicit_preview=explicit)
                self.assertEqual(code, 0)
                self.assertIs(report["acted"], False)
                self.assertIs(report["dry_run"], True)
                self.assertEqual(report["method"], "preview")
                self.assertEqual(world.events, [])
                self.assertEqual(world.actions, [])

    def test_dispatch_failure_remains_unknown_without_fallback(self):
        for method in ("invoke", "coord"):
            with self.subTest(method=method):
                world = World(dispatch_failure=True)
                code, report = world.cli(method)
                self.assertEqual(code, 5)
                self.assertIs(report["acted"], None)
                self.assertEqual(report["error"], "action_outcome_unknown")
                self.assertEqual(world.actions, [method])
                self.assertEqual(world.events[-2:], ["readiness", "dispatch:" + method])

    def test_missing_readiness_probe_refuses(self):
        with self.subTest(probe="absent"):
            world = World()
            del world.common.has_interactive_desktop
            self.assert_refused(world, world.cli("invoke"))
            self.assertEqual(world.events, ["dpi"])
