"""Generated by tools/make_fixtures.py; synthetic pointer-movement dispatch regressions."""
import argparse
import ast
import builtins
import copy
import io
import json
import math
from pathlib import Path
from types import SimpleNamespace
import unittest

ROOT = Path(__file__).resolve().parents[1]


def production_source(name):
    return (ROOT / "skills/screen-vision/scripts" / name).read_bytes()


def generator_source():
    return (ROOT / "tools/make_fixtures.py").read_bytes()


def regression_source():
    return Path(__file__).read_bytes()


def record():
    return {
        "id": 0, "type": "button", "label": "Acme action", "name": "Acme action",
        "automation_id": "acme-action", "class_name": "Button", "source": "uia",
        "rect": [10, 20, 50, 60], "center": [30, 40], "enabled": True,
        "offscreen": False, "clickable": True, "patterns": [],
        "captured_at": 1000.0, "capture_rect": [0, 0, 200, 200],
        "identity": {
            "runtime_id": [42, 7], "window_runtime_id": [42, 1],
            "window": {"hwnd": 101, "pid": 202, "process_started": 303,
                       "rect": [0, 0, 200, 200]},
        },
    }


def variants(double=None):
    return [(method, button, twice)
            for method in ("coord", "auto")
            for button in ("left", "right", "middle")
            for twice in (False, True)
            if double is None or twice is double]


def selected(source, names, namespace):
    nodes, found = [], set()
    for node in ast.parse(source).body:
        if isinstance(node, (ast.FunctionDef, ast.ClassDef)) and node.name in names:
            nodes.append(node)
            found.add(node.name)
        elif isinstance(node, ast.Assign) and len(node.targets) == 1:
            target = node.targets[0]
            if isinstance(target, ast.Name) and target.id in names:
                nodes.append(node)
                found.add(target.id)
    assert found == names
    exec(compile(ast.Module(body=nodes, type_ignores=[]), "selected-production.py", "exec"),
         namespace)


class World:
    def __init__(self, fault=None, *, phase="move", pattern=False):
        self.saved = record()
        self.window = copy.deepcopy(self.saved["identity"]["window"])
        self.fault, self.phase, self.pattern = fault, phase, pattern
        self.trace, self.buttons, self.injected_targets, self.output = [], [], [], []
        self.ready, self.now, self.pointer = True, 1001.0, (30, 40)
        self.moved = self.changed = self.hit_error = self.identity_error = False
        self.argv, self.invoke_calls = [], 0
        world = self

        class Control:
            def __init__(self, runtime, *, root=False):
                self.runtime = list(runtime)
                self.record = copy.deepcopy(world.saved)
                self.NativeWindowHandle, self.ProcessId = 101, 202
                self.children = []
                if root:
                    self.record["rect"] = [0, 0, 200, 200]

            def GetRuntimeId(self): return self.runtime
            def GetChildren(self): return self.children
            @property
            def BoundingRectangle(self):
                return SimpleNamespace(**dict(zip(("left", "top", "right", "bottom"),
                                                 self.record["rect"])))
            @property
            def Name(self): return self.record["name"]
            @property
            def AutomationId(self): return self.record["automation_id"]
            @property
            def ClassName(self): return self.record["class_name"]
            @property
            def ControlTypeName(self): return self.record["type"].capitalize() + "Control"
            @property
            def IsEnabled(self): return self.record["enabled"]
            @property
            def IsOffscreen(self): return self.record["offscreen"]
            def GetInvokePattern(self): return self if world.pattern else None
            def GetTogglePattern(self): return None
            def GetSelectionItemPattern(self): return None
            def GetExpandCollapsePattern(self): return None
            def Invoke(self):
                world.trace.append("invoke")
                world.invoke_calls += 1

        self.control = Control([42, 7])
        self.root = Control([42, 1], root=True)
        self.root.children = [self.control]
        self.replacement = Control([42, 999])
        self.hit = self.control

        def from_handle(hwnd):
            self.trace.append("resolve")
            assert hwnd == 101
            return self.root

        def from_point(x, y):
            self.trace.append("hit")
            assert (x, y) == (30, 40)
            if self.hit_error:
                raise RuntimeError("synthetic hit-test unavailable")
            return self.hit

        def window_identity(hwnd):
            self.trace.append("identity")
            if self.identity_error:
                raise RuntimeError("synthetic window identity unavailable")
            if hwnd != self.window["hwnd"]:
                return None
            return copy.deepcopy(self.window)

        class Point:
            def __init__(self): self.x = self.y = 0

        class User32:
            def SetCursorPos(self, x, y):
                world.trace.append("move")
                if world.fault == "move-error":
                    raise OSError("synthetic movement failure")
                if world.fault == "move-false":
                    return 0
                world.pointer, world.moved = (x, y), True
                world.change("move")
                return 1

            def GetCursorPos(self, ref):
                world.trace.append("position")
                if world.fault == "read-error":
                    raise OSError("synthetic pointer query failure")
                if world.fault == "read-false":
                    return 0
                ref._obj.x, ref._obj.y = world.pointer
                return 1

            def mouse_event(self, flags, *args):
                down = flags in (0x0002, 0x0008, 0x0020)
                world.trace.append("down" if down else "up")
                world.buttons.append(flags)
                world.injected_targets.append(None if world.hit is None else list(world.hit.runtime))
                if down and world.fault in ("down-error", "both-error"):
                    raise OSError("synthetic error after down may have reached target")
                if not down:
                    if len(world.buttons) == 2:
                        world.change("after-first-up")
                    if world.fault in ("up-error", "both-error"):
                        raise OSError("synthetic error after up may have reached target")

        ctypes_facade = SimpleNamespace(
            windll=SimpleNamespace(user32=User32()),
            byref=lambda point: SimpleNamespace(_obj=point),
            wintypes=SimpleNamespace(POINT=Point),
        )

        def common_import(name, *args, **kwargs):
            assert name == "ctypes"
            return ctypes_facade

        common_ns = {
            "__builtins__": dict(vars(builtins), __import__=common_import),
            "ctypes": ctypes_facade, "IS_WINDOWS": True,
            "require_physical_coordinates": lambda: self.trace.append("dpi"),
            "window_identity": window_identity,
        }
        selected(production_source("_common.py"),
                 {"click_physical", "control_identity", "runtime_id"}, common_ns)
        self.common = SimpleNamespace(
            IS_WINDOWS=True, has_interactive_desktop=self.readiness,
            require_physical_coordinates=common_ns["require_physical_coordinates"],
            control_identity=common_ns["control_identity"], runtime_id=common_ns["runtime_id"],
            click_physical=common_ns["click_physical"],
        )
        auto = SimpleNamespace(ControlFromHandle=from_handle, ControlFromPoint=from_point)

        def click_import(name, *args, **kwargs):
            assert name == "uiautomation"
            return auto

        class Parser(argparse.ArgumentParser):
            def parse_args(self, args=None, namespace=None):
                return super().parse_args(world.argv if args is None else args, namespace)

        def input_file(path, *args, **kwargs):
            assert path == "synthetic-elements.json"
            return io.StringIO(json.dumps([self.saved]))

        self.click = {
            "__doc__": "Synthetic pointer movement contract.",
            "__builtins__": dict(vars(builtins), __import__=click_import),
            "C": self.common, "math": math, "json": json,
            "time": SimpleNamespace(time=lambda: self.now, monotonic=lambda: 1.0),
            "argparse": SimpleNamespace(ArgumentParser=Parser),
            "open": input_file, "print": lambda value: self.output.append(json.loads(value)),
        }
        selected(production_source("click.py"),
                 {"ActionError", "find_element", "validate_capture", "validate_control",
                  "require_ready_desktop", "resolve_element", "act_on_element", "main",
                  "MAX_CAPTURE_AGE", "PATTERNS"}, self.click)

    def change(self, phase):
        if self.changed or phase != self.phase:
            return
        self.changed = True
        fault = self.fault
        if fault == "hover-replacement": self.hit = self.replacement
        elif fault == "hover-empty": self.hit = None
        elif fault == "runtime": self.control.runtime = [42, 999]
        elif fault == "window-runtime": self.root.runtime = [42, 999]
        elif fault in ("hwnd", "pid", "process_started"):
            self.window[fault] += 1
        elif fault == "window-rect": self.window["rect"] = [0, 0, 210, 210]
        elif fault == "geometry": self.control.record["rect"] = [20, 20, 60, 60]
        elif fault == "disabled": self.control.record["enabled"] = False
        elif fault == "offscreen": self.control.record["offscreen"] = True
        elif fault in ("name", "automation_id", "class_name"):
            self.control.record[fault] = "Acme replacement"
        elif fault == "type": self.control.record["type"] = "text"
        elif fault == "capture-age": self.now = 1061.0
        elif fault == "ready-false": self.ready = False
        elif fault == "ready-none": self.ready = None
        elif fault == "ready-error": self.ready = OSError("synthetic readiness query failure")
        elif fault == "hit-error": self.hit_error = True
        elif fault == "identity-error": self.identity_error = True
        elif fault == "wrong-position": self.pointer = (300, 400)

    def readiness(self):
        self.trace.append("readiness")
        if self.moved and self.fault == "late-pointer-drift":
            self.pointer = (300, 400)
        if isinstance(self.ready, Exception):
            raise self.ready
        return self.ready

    def cli(self, method="coord", button="left", double=False):
        self.argv = ["--elements-json", "synthetic-elements.json", "--id", "0",
                     "--method", method, "--button", button, "--confirm"]
        if double:
            self.argv.append("--double")
        code = self.click["main"]()
        assert len(self.output) == 1
        return code, self.output[0]


class Screen19MovementTests(unittest.TestCase):
    def assert_refused(self, world, result, code="recapture_required"):
        status, report = result
        self.assertEqual(status, 5)
        self.assertIs(report["ok"], False)
        self.assertIs(report["acted"], False)
        self.assertEqual(report["error"], code)
        self.assertEqual(world.buttons, [])
        self.assertEqual(world.invoke_calls, 0)

    def test_unchanged_target_revalidated_after_movement_before_each_pair(self):
        for method, button, double in variants():
            with self.subTest(method=method, button=button, double=double):
                world = World()
                status, report = world.cli(method, button, double)
                self.assertEqual(status, 0)
                self.assertIs(report["acted"], True)
                flags = {"left": [2, 4], "right": [8, 16], "middle": [32, 64]}[button]
                self.assertEqual(world.buttons, flags * (2 if double else 1))
                self.assertEqual(world.trace.count("move"), 1)
                self.assertEqual(world.trace.count("hit"), 3 if double else 2)
                self.assertTrue(all(value == [42, 7] for value in world.injected_targets))
                for index, event in enumerate(world.trace):
                    if event == "down":
                        self.assertEqual(world.trace[index - 2:index], ["readiness", "position"])
                self.assertEqual(world.invoke_calls, 0)

    def test_movement_changes_target_window_capture_or_readiness_refuses_before_buttons(self):
        faults = ("hover-replacement", "hover-empty", "runtime", "window-runtime",
                  "hwnd", "pid", "process_started", "window-rect", "geometry",
                  "disabled", "offscreen", "name", "automation_id", "class_name", "type",
                  "capture-age", "ready-false", "ready-none", "ready-error",
                  "hit-error", "identity-error")
        for fault in faults:
            for method, button, double in variants():
                with self.subTest(fault=fault, method=method, button=button, double=double):
                    world = World(fault)
                    code = "no_interactive_desktop" if fault.startswith("ready-") else "recapture_required"
                    self.assert_refused(world, world.cli(method, button, double), code)
                    self.assertEqual(world.trace.count("move"), 1)

    def test_movement_and_pointer_query_failures_emit_no_buttons(self):
        for fault in ("move-false", "move-error", "read-false", "read-error",
                      "wrong-position", "late-pointer-drift"):
            for method, button, double in variants():
                with self.subTest(fault=fault, method=method, button=button, double=double):
                    world = World(fault)
                    self.assert_refused(world, world.cli(method, button, double))
                    self.assertEqual(world.trace.count("move"), 1)

    def test_second_pair_refusal_is_unknown_without_retry(self):
        for fault in ("hover-replacement", "runtime", "ready-false", "ready-error",
                      "hit-error", "wrong-position", "capture-age"):
            for method, button, double in variants(double=True):
                with self.subTest(fault=fault, method=method, button=button):
                    world = World(fault, phase="after-first-up")
                    status, report = world.cli(method, button, double)
                    self.assertEqual(status, 5)
                    self.assertIs(report["acted"], None)
                    self.assertEqual(report["error"], "action_outcome_unknown")
                    self.assertEqual(world.buttons, {"left": [2, 4], "right": [8, 16],
                                                     "middle": [32, 64]}[button])
                    self.assertEqual(world.trace.count("move"), 1)
                    self.assertEqual(world.invoke_calls, 0)

    def test_dispatch_errors_attempt_matching_release_once_and_never_retry(self):
        for fault in ("down-error", "up-error", "both-error"):
            for method, button, double in variants():
                with self.subTest(fault=fault, method=method, button=button, double=double):
                    world = World(fault)
                    status, report = world.cli(method, button, double)
                    self.assertEqual(status, 5)
                    self.assertIs(report["acted"], None)
                    self.assertEqual(report["error"], "action_outcome_unknown")
                    self.assertEqual(world.buttons, {"left": [2, 4], "right": [8, 16],
                                                     "middle": [32, 64]}[button])
                    self.assertEqual(world.trace.count("down"), 1)
                    self.assertEqual(world.trace.count("up"), 1)
                    self.assertEqual(world.trace.count("move"), 1)
                    self.assertEqual(world.invoke_calls, 0)

    def test_uia_action_does_not_move_or_inject_mouse_buttons(self):
        for method in ("invoke", "auto"):
            with self.subTest(method=method):
                world = World("hover-replacement", pattern=True)
                status, report = world.cli(method)
                self.assertEqual(status, 0)
                self.assertEqual(report["method"], "invoke:Invoke")
                self.assertIs(report["acted"], True)
                self.assertEqual(world.buttons, [])
                self.assertNotIn("move", world.trace)
                self.assertEqual(world.invoke_calls, 1)

    def test_generator_reproduces_regression(self):
        namespace = {}
        selected(generator_source(), {"action_movement_test_source"}, namespace)
        self.assertEqual(namespace["action_movement_test_source"]().encode("utf-8"),
                         regression_source())
